[package]
name = "Chip-8_emu"
version = "0.1.0"
authors = ["NinVoido"]
edition = "2021"
[features]

[dependencies]
egui = "0.18"
egui-wgpu = "0.18"
egui-winit = { version = "0.18", default-features = false, features = ["links"] }
pixels = "0.9.0"
winit = "0.26"
winit_input_helper = "0.12"
